appName: atlas-api
namespace: atlas-apps
fullnameOverride: "atlas-api"


replicaCount: 2

image:
  repository: 047631362165.dkr.ecr.us-east-1.amazonaws.com/fastapi-repo
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  name: atlas-api
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx

  # hosts:
  #   - host: azubuikeokom.com
  #     paths:
  #       - path: /
  #         pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi

  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 25
  maxReplicas: 
  targetCPUUtilizationPercentage: 70