apiVersion: apps/v1
kind: Deployment

metadata:
  name: atlas-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: atlas-api

  template:
    metadata:
      labels:
        app: atlas-api

    spec:
      containers:
        - name: fastapi-chart

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            limits:
              cpu: 500m
              memory: 512Mi

            requests:
              cpu: 250m
              memory: 256Mi